### ISSUE TITLE
TypeError: Cannot read property 'scan' of undefined

### ISSUE THREAD

**Issue by jasenkabalac** [balthazar/react-native-zeroconf#102]
I'm using your sample app in Expo .
 zeroconf.scan('http', 'tcp', 'local.') is not working

**Comment by jkaravakis** [comment]
I am having the same issue. I am not using Expo and am using React Native v0.61.2 and react-native-zeroconf v0.11.4.

**Comment by jkaravakis** [comment]
Hey @jasenkabalac restarting my metro bundler worked for me!
