### ISSUE TITLE
How to scan Websockets?

### ISSUE THREAD

**Issue by vedant-dobby** [balthazar/react-native-zeroconf#104]
Hi I'm trying to scanning MQTT ports and I got success. I want to whether I can directly search for a specific port without specifying the type of the port. For eg. I want to search for websockets which is port 9001. How can I do that?

**Comment by vedant-dobby** [comment]
@balthazar

**Comment by balthazar** [comment]
You might want to read a little more about Zeroconf to get a better answer, but I think you should be able to as the default type is tcp and that's what websockets are using
