### ISSUE TITLE
'error: unhandled error: (undefined)' on ios

### ISSUE THREAD

**Issue by vtn-dev2016** [balthazar/react-native-zeroconf#126]
when i go to settings wifi my app is running in background when i comeback again i found ![103671435_2646913052297636_5115833771188916016_n](https://user-images.githubusercontent.com/30209508/84594659-159dd900-ae7e-11ea-8fed-4df7580a5047.jpg)

**Comment by dotemacs** [comment]
Hello @vtn-dev2016 

I'm not a maintainer of this package.

But do you have anything else to go on apart from this screenshot?

Can you try to create a minimum reproducible app and share it somewhere publicly on GitHub?

I can't guarantee that I'll solve the problem, but at least it'll give us a bit more to go on.

**Comment by vtn-dev2016** [comment]
I have encountered a problem.  i has duplicate new Zeroconf() thanks.
