### ISSUE TITLE
Cannot start scan on iOS14

### ISSUE THREAD

**Issue by mayue3434** [balthazar/react-native-zeroconf#148]
iPhone 8p, iOS14,
"react-native": "0.62.2",
"react-native-zeroconf": "^0.12.4",

I run the example but failed, even cannot start scan:
![scan](https://user-images.githubusercontent.com/19703139/102333072-dfc1e480-3fc7-11eb-8a9c-8ab679d443ea.gif)

And I get the error code:
![image](https://user-images.githubusercontent.com/19703139/102332724-7346e580-3fc7-11eb-92cc-cff501710669.png)

Does anyone know how to solve it?

**Comment by DennisSnijder** [comment]
Make sure you specificy the service you're scanning for.
https://github.com/balthazar/react-native-zeroconf#ios-14-permissions

**Comment by mayue3434** [comment]
Yes. I have added them. Here is my Info.plist:
![image](https://user-images.githubusercontent.com/19703139/102986193-64be7800-454b-11eb-8361-fa63b38dbf8a.png)
But still the same error

**Comment by ilyalezhnev** [comment]
The same issue. Is there a solution? My ios app have been crashed on .scan() method.

**Comment by calinbodnar** [comment]
@ilyalezhnev @mayue3434 Make sure the Bonjour service in the plist is an actual service, as in _your-bonjour-service._tcp -> this works for me.

**Comment by stevelacy** [comment]
In my case I was searching for an Arduino service. My values on iOS 14:
Info.plist
```
<key>NSBonjourServices</key>
<array>
	<string>_arduino._tcp.</string>
</array>

```

Scan:
```js
zeroconf.scan('arduino', 'tcp') // _arduino._tcp
```

**Comment by mayue3434** [comment]
You inspire me. I modify my code to:
Info.plist
```
<key>NSBonjourServices</key>
<array>
	<string>_http._tcp.</string>
</array>
```
js code:
```
zeroconf.scan('http', 'tcp')
```
It works. Thank you all so much.
