### ISSUE TITLE
How to discover all discoverable devices

### ISSUE THREAD

**Issue by nxtexe** [balthazar/react-native-zeroconf#150]
It seems zeroconf is not working for me on react native version 0.63.3. It is a none expo react app being tested on physical device. I registered a listener for all possible events and none fire. getServices() also returns {}. I know my service is working since I can ping the service from windows command line. Ideas?

**Comment by jwh-hutchison** [comment]
I have the same issue, have you checked if you receive anything in the found event call? I can pick up the service name but the service never actually resolves.

**Comment by nxtexe** [comment]
What I did to solve the issue, I used bonjour browser on windows to discover the device. It came up as type: _workstation._tcp, now in react native zeroconf scan method instead of passing http as type I passed workstation as type i.e. ```scan('workstation', 'tcp', '.local');```, this works. I figured this out due to the docs saying when trying to advertise you need to pass name and type underscore prefixed with a dot separating type and protocol for the type argument i.e. _http._tcp. So what I did was try to advertise using ```publishService('_http._tcp', 'tcp', 'local', 'device', 8000, {'NAME': 'NULL'})```, then tried to discover it in the same script with ```scan('http', 'tcp', '.local');``` and it worked! In bonjour browser my phone came up as _http._tcp. So all I did was tried the same thing for the raspberry pi I was originally trying to discover and it worked.

**Comment by nxtexe** [comment]
Sorry for the long winded reply but this is so confusing I hope this explains it perfectly to the next wanderer. I may open a PR to make it clearer.

**Comment by jwh-hutchison** [comment]
> What I did to solve the issue, I used bonjour browser on windows to discover the device. It came up as type: _workstation._tcp, now in react native zeroconf scan method instead of passing http as type I passed workstation as type i.e. `scan('workstation', 'tcp', '.local');`, this works. I figured this out due to the docs saying when trying to advertise you need to pass name and type underscore prefixed with a dot separating type and protocol for the type argument i.e. _http._tcp. So what I did was try to advertise using `publishService('_http._tcp', 'tcp', 'local', 'device', 8000, {'NAME': 'NULL'})`, then tried to discover it in the same script with `scan('http', 'tcp', 'local');` and it worked! In bonjour browser my phone came up as _http._tcp. So all I did was tried the same thing for the raspberry pi I was originally trying to discover and it worked.

Was the resolved event ever called though?

**Comment by nxtexe** [comment]
Yea everything works fine now.

**Comment by jwh-hutchison** [comment]
I got mine working, turns out battery optimizations were causing the resolve failures, I set com.android.server.NetworkPermissionConfig to 'don't optimise' in my android settings under: Apps & Notifications -> Advanced -> Special App Access -> Battery Optimization, now it works every time.

**Comment by shoaibarif244** [comment]
@nxtexe 
can you please guide me that how to use it??
