### ISSUE TITLE
Android Version

### ISSUE THREAD

**Issue by TokeyChan** [balthazar/react-native-zeroconf#190]
Hello!

Great package, just one thing: It may be important for people to know that this package will only work on Android ~12 upwards!

Maybe add that in your readme

**Comment by balthazar** [comment]
Hello Tokey, yeah that sounds good. Is there a specific dependency that makes this version requirement a thing?

**Comment by TokeyChan** [comment]
DNS Resolver  |  Android Open Source Projectsource.android.comIf you scroll down to the last section it says „November 2021“ which should be Android 12L and later. Am 15.11.2024 um 20:50 schrieb balthazar ***@***.***>:﻿
Hello Tokey, yeah that sounds good. Is there a specific dependency that makes this version requirement a thing?
