### ISSUE TITLE
Expo undefined is not an object (evaluating 'RNZeroconf.scan') 

### ISSUE THREAD

**Issue by iparianos** [balthazar/react-native-zeroconf#48]
- node_modules/react-native-zeroconf/dist/index.js:81:11 in scan,

Dear All,

Good morning, since new to react-native, but old dog on ObjC/Swift dev, I'm facing the above error when trying to use the Zeroconf module. The same error appears on Android too. I've followed the instructions below:
npm i -S react-native-zeroconf
react-native install react-native-zeroconf
react-native link react-native-zeroconf
Everything seemd to be correct, I'm getting "rnpm-install info Module react-native-zeroconf has been successfully installed & linked", but when I built it on an Android device, guess what red screen and the error on the title. 

node -v : v6.11.3
npm -v : 5.4.2
"native-base": "^2.3.2",
"react": "^16.0.0-alpha.12",
"react-native": "^0.48.4",
"expo": "^21.0.0",

and Zeroconf version 0.8.3

import Zeroconf from 'react-native-zeroconf';
const zeroconf = new Zeroconf();
zeroconf.scan(); 
Then error.. 
As I understand it can't find the "const RNZeroconf = NativeModules.RNZeroconf"
thank you all in advance.

**Comment by nomoreboredom** [comment]
You can't use native modules with Expo as far as I know, you will need to unmount RN project from Expo to native code.

**Comment by iparianos** [comment]
My first thought was this..But I didn't want to believe it..!I will give a try, thanks!

**Comment by everyusernameistaken123** [comment]
Hello all,

I try to use this module for 2 days now, I always end up in the described error ("TypeError: undefined is not an object (evaluating 'RNZeroconf.scan')")

I found some issues here describing the same error - they all have Expo as root cause as far as I understand?
After all the troubles with "ejecting", I started a new project with "react-native init" and just edited 2 files:

package.json:
```
...
"dependencies": {
    "react": "16.0.0",
    "react-native": "0.50.3",
    "react-native-tcp": "^3.3.0",
    "react-native-zeroconf": "^0.8.3"
  }
...
```

app.js:
```
...
import Zeroconf from 'react-native-zeroconf'

export default class App extends Component<{}> {
    componentDidMount() {
        console.warn("Starting scan...");
        zeroconf = new Zeroconf();
        zeroconf.scan('http', 'tcp', 'local.');
      }
...
```

**Comment by Rumidom** [comment]
that's sad, is there any way to make it work with Expo?

**Comment by Rumidom** [comment]
yeah, i wish it would work on expo as well, if you want this module on expo please vote for it on expo's feature-requests: https://expo.canny.io/feature-requests/p/zeroconf-protocol-support , for now the only way is to detach

**Comment by aprilmintacpineda** [comment]
Some months later. It doesn't seem like there's any movement.

**Comment by balthazar** [comment]
As @nomoreboredom, using Expo prevents you from using native modules, which react-native-zeroconf is. You need to eject or wait for the canny feature request (but it may take a while). I'm going to have a bit of time to get back on this module and create a full example #73. For people getting an `undefined` `RNZeroconf`, it's likely you have your module not installed correctly.

@aprilmintacpineda Complaining doesn't help! Are you willing to make any PR?
