### ISSUE TITLE
Publish MDNS services

### ISSUE THREAD

**Issue by makeitnew** [balthazar/react-native-zeroconf#49]
Hi..

Anyone interested in using this package for publishing services?

The APIs on both iOS and Android are simple enough. I may submit a PR if @Apercu thinks this is the right place for the functionality. Otherwise, I'll create a separate package.

**Comment by Apercu** [comment]
Hey, you mean to advertise a service directly from the native app? I guess it could be a functionality yes!

**Comment by makeitnew** [comment]
That's correct. I have a use case where one app will publish (advertise) a service to other clients on local network. I'll send out an API proposal before I get started sometime in the next 2-3 weeks.

**Comment by Apercu** [comment]
Nice thanks!

**Comment by jalieven** [comment]
Any progress on this enhancement? I am planning to implement this if nobody has already done so. Will need some help on iOS since I'm not well versed in Objective C. But I could take a stab at it.

**Comment by makeitnew** [comment]
I moved on to another project. However, I do have an iOS implementation
(but not Android yet). I can publish that in about a week. Maybe we can
merge Android and iOS versions.

**Comment by jalieven** [comment]
@makeitnew I have added you as a collaborator on my fork: https://github.com/jalieven/react-native-zeroconf. I have already added the placeholder register/unregister react methods in iOS. Would be nice to inject your iOS code in there. I can test it an create a pull request for @balthazar

**Comment by shanekoss** [comment]
Very interested in this.  Any news?  Happy to help if I can.  Cheers.

**Comment by makeitnew** [comment]
I'll add my code in the next day.

**Comment by makeitnew** [comment]
Please have a look at https://github.com/makeitnew/react-native-zeroconf.git.
This fork contains both my iOS implementation and an Android
implementation, (I actually didn't remember I'd done the Android version
too as I've been away from this project for several months.)

Anyway, please take a look and let me know. I understand our interfaces
probably aren't identical. I can either adopt my code to use yours; or if
you prefer mine, then vice versa.

Please note that I'm not doing an RN work currently. So I might not have a
proper test environment immediately available.

Lastly, apologies for taking so long to respond. I've been traveling for
the last month.

**Comment by weswes** [comment]
@makeitnew Could you please submit a PR ? I've tested on iOS and confirm it works.

**Comment by makeitnew** [comment]
I’ll submit a PR today.
