### ISSUE TITLE
Android: NsdServiceInfo getAttributes added in API level 21

### ISSUE THREAD

**Issue by szakhlypa** [balthazar/react-native-zeroconf#52]
Hi, thanks for this package.

https://github.com/balthazar/react-native-zeroconf/blob/develop/android/src/main/java/com/balthazargronon/RCTZeroconf/ZeroconfModule.java#L144

getAttributes method of NsdServiceInfo was added in API 21 ( https://developer.android.com/reference/android/net/nsd/NsdServiceInfo.html#getAttributes() ) 
so older Android devices throws java.lang.NoSuchMethodError .

**Comment by jsdario** [comment]
Can we have some more info about this for someone to cook a patch?
I am experiencing this on a significant portion of my user base

**Comment by balthazar** [comment]
You can use and pin to the `0.8.2` version, that doesn't implement [this commit](https://github.com/balthazar/react-native-zeroconf/commit/f810f94d52241e718bf397afd89a7dc08c164fb2)

**Comment by thehellmaker** [comment]
Hi @balthazar,
Can we add a version check for this part of the code rather than using older version? 
Cheers
Akash A

**Comment by thehellmaker** [comment]
I can send a PR for this request if you are ok with it?

**Comment by balthazar** [comment]
Yes would be great!

**Comment by thehellmaker** [comment]
@balthazar I do not have permission to raise a pull request. Please do provide be perms on this repo
