### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'RNZeroconf.scan')

### ISSUE THREAD

**Issue by fabdrol** [balthazar/react-native-zeroconf#59]
I'm working on an app for a `C67ML_Carta2_Plus` Android e-reader. Sadly, the e-reader runs an ancient version of Android, 4.2.2.

I'm getting the following error: `TypeError: undefined is not an object (evaluating 'RNZeroconf.scan')`. My question is: is Android 4.2.2 supported an, if so, how do I get it to work?

**Comment by Bobozee** [comment]
You should rebuild the project after module installation. Restarting by clearing the cache is not enough.

**Comment by balthazar** [comment]
As @mitevdev it looks like your module is not installed properly. Make sure you double check that

**Comment by balthazar** [comment]
For future readers, you most likely haven't ran`react-native link`.
