### ISSUE TITLE
RNZeroconf is undefined

### ISSUE THREAD

**Issue by Bobozee** [balthazar/react-native-zeroconf#61]
This statement in index.js returns 'undefined':

`var RNZeroconf=_reactNative.NativeModules.RNZeroconf;`

It is strange because the module is linked and the project compiled. What might I have done wrong?

```
import Zeroconf from 'react-native-zeroconf';
zeroconf = new Zeroconf();

for(prop in this.zeroconf) {
    console.log(prop);
}
```

shows the following:

_events
_maxListeners
_services
_dListeners
setMaxListeners
emit
addListener
on
once
removeListener
removeAllListeners
listeners
listenerCount

the call:

`zeroconf.scan();`

leads to:

> TypeError: Cannot read property 'scan' of undefined

**Comment by robson3999** [comment]
Hi,
you should initialize zeroconf with `const`:
`const zeroconf = new Zeroconf()` instead of `zeroconf = new Zeroconf()`

**Comment by Bobozee** [comment]
Sorry, any fault. The project was actually not rebuild after I have installed the module. All is fine.
