### ISSUE TITLE
requiresMainQueueSetup method is missing

### ISSUE THREAD

**Issue by mitevdev** [balthazar/react-native-zeroconf#62]
> YellowBox.js:80 Module RNZeroconf requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.

It should be something like this:

```
+ (BOOL)requiresMainQueueSetup
{
    return YES;
}
```

**Comment by westcode** [comment]
Sure you are using the latest version? https://github.com/balthazar/react-native-zeroconf/commit/b9b863a610bf7ae0cac102ae082c987ef5fc0fdb#diff-52c59cceb39162c1d1350b424b6c8ace

**Comment by SuperBesse** [comment]
I propose this PR to fix it:
https://github.com/balthazar/react-native-zeroconf/pull/94
