### ISSUE TITLE
Unable to discover MDNS services

### ISSUE THREAD

**Issue by LaurieWilliamsNZ** [balthazar/react-native-zeroconf#68]
Unable to discover MDNS services on iOS with react-native-zeroconf , however after performing a scan via Fing (iOS app) I am able to discover and resolve successfully again with react-native-zeroconf.

Any suggestions on how to resolve this?

**Comment by balthazar** [comment]
Not sure to be honest, might require a bit more info/data. Are you able to debug? How are you broadcasting your service?

**Comment by balthazar** [comment]
Just tried the example and don't have any issue on iOS. Maybe try this one?

**Comment by rolandjitsu** [comment]
I seem to be having the same issue. I'm publishing a bonjour service using a simple nodejs [bonjour](https://www.npmjs.com/package/bonjour) package.
