### ISSUE TITLE
Android NSD does not resolved(nothing found) services on Android P

### ISSUE THREAD

**Issue by fishkingsin** [balthazar/react-native-zeroconf#72]
Guys, I am testing on Pixels 3 Android P, unfortunately, it doesn't work, 
I am trying to migrate from android dns android.net.nsd.NsdServiceInfo 
to
javax.jmdns.JmDNS;
https://github.com/jmdns/jmdns

here is the changes
https://github.com/nixplay/react-native-zeroconf/tree/develop
can anyone feed back and help to improve it ?

**Comment by balthazar** [comment]
Doesn't work -> can you be more specific?

**Comment by fishkingsin** [comment]
@balthazar Android NSD does not resolved(nothing found, nothing response) services

**Comment by balthazar** [comment]
Are you sure this is an issue with the NsdService or with your emitter? Did you make it work with jmDNS?

**Comment by fishkingsin** [comment]
I migrated from https://github.com/becvert/cordova-plugin-zeroconf
And already tested

James Kong

**Comment by balthazar** [comment]
I think I'm running onto the same issue using the Android example I just pushed.

**Comment by balthazar** [comment]
No idea, but looking at jmdns they seem to have lots of issues too.

**Comment by rolandjitsu** [comment]
@balthazar I'm having a similar issue. Services are discovered, but never resolved. Do you know how I can fix this sort of issue?
