### ISSUE TITLE
iOS build error

### ISSUE THREAD

**Issue by Hadjimina** [balthazar/react-native-zeroconf#76]
Hi,

I have been trying for an entire day to get it to build and I am now in serious need for help. 
On android it works perfectly and the setup was super easy, however on iOS it's a nightmare. 

I setup everything like the docs say when setting up a react native app (I am using expokit btw) and everything works fine. However when I try to build it I get this error:

`/node_modules/react-native-zeroconf/ios/RNZeroconf/RNZeroconf.h:10:9: 'React/RCTBridge.h' file not found`

I think there is also something wrong with the way we currently import RCTBridge
`#import <React/RCTBridge.h>`
from what I have read I think the syntax changed. 

My problem looks to be quite similar to  #28 but changing the import statement to the one listed there simply yields the same error again. 

Do you have any idea on how to fix this?
Thanks for your help

What I have tried so far:

- Using  Legacy build system
- Removing parallelized builds & adding React manually to the build targets (and making sure its the topmost entry in the list)
- Adding "${SRCROOT}/…/…/ios/Pods/Headers/Public" to header search paths

**Comment by balthazar** [comment]
Hey, I'm guessing this is an issue with the React version being too high and they changed something with the Bridge.

What RN version are you using?

**Comment by Hadjimina** [comment]
This one:

react-native: 0.57.1

**Comment by Hadjimina** [comment]
Hey any update on this issue?

**Comment by Hadjimina** [comment]
Never mind figured it out. My mistake...

**Comment by wbrickner** [comment]
@Hadjimina Please tell me what the solution was?  I am stuck with this exact issue.

**Comment by Hadjimina** [comment]
I had to add `${SRCROOT}/…/…/ios/Pods/Headers/Public` and something like `${SRCROOT}/…/…/ReactNative` (super unsure about the second one, but it was something like that) to both Project and Target of the library that failed to build. Good luck

**Comment by wbrickner** [comment]
Okay. I will try some things and report back with my solution for posterity.

**Comment by TobyEalden** [comment]
Still getting this error, using RN v0.60.5.

The manual linking documentation is incorrect - the header path should be set to:

```
${SRCROOT}/../../../ios/Pods/Headers/Public/React-Core
```

You may also need to add a `react-native.config.js` to exclude this library from auto-linking.

**Comment by balthazar** [comment]
@TobyEalden Feel free to submit a PR if you have the time 🙂

**Comment by Christopotamus** [comment]
@TobyEalden you saved my sanity with that.

@balthazar I've edited the wiki to add the line for ios >= RN 0.60.0 until we can get a PR
