### ISSUE TITLE
Addresses array and host recommendation?

### ISSUE THREAD

**Issue by tedhenry100** [balthazar/react-native-zeroconf#80]
iOS's NSNetService [addresses property](https://developer.apple.com/documentation/foundation/nsnetservice/1408528-addresses?language=objc) is an array of possibly multiple addresses.

Android's NsdServiceInfo [ultimately returns just one address](https://developer.android.com/reference/java/net/InetAddress.html#getHostAddress()). react-native-zeroconf wraps this address in an array to maintain a uniform API with the iOS result.

If requests to a discovered service are to be made using an address, which address to choose from the array? The first one? The last one? It doesn't matter?

react-native-zeroconf service info also includes a `host` key. The value is the host name on [iOS](https://developer.apple.com/documentation/foundation/nsnetservice/1413300-hostname?language=objc) and [Android](https://developer.android.com/reference/java/net/InetAddress.html#getHostName()).

Is it better to use this host value than using one of the addresses when making requests to the discovered service? If not, when might the host name be useful?

_Thanks!!_

**Comment by balthazar** [comment]
The iOS array is probably there to support iPv4 and iPv6 for the same host. I would say just take the first personally

**Comment by tedhenry100** [comment]
Thank you.

**Comment by StefanWallin** [comment]
I've been thinking about this and came up with promise type where I race the potential addresses against a status-endpoint on the server and take the address that responds first. For me, _uncertain if it's only in development with the react-native remote debugging turned on_, I've discovered that the ipv6-addresses throw a typeError from within fetch, so just taking the first is not something I'd recommend.

Here's that `AnySuccessFulPromise` promise  type:
https://gist.github.com/StefanWallin/e42b8d69b9e3a068e0e41ee86c4f9925

```javascript
function discoverConnectableHost(hosts, server) {
  const hostPromises = [];
  hosts.forEach(host => {
    hostPromises.push(status(host, server.port));
  });
  return new AnySuccesfulPromise(hostPromises)
}
```
Here's how you'd call that.
```javascript
zeroconf.on('resolved', (result) => {
  const { server } = result;
  const potentialHosts = deduplicateArray(server.addresses);
  discoverConnectableHost(potentialHosts, server).then((succcessfulFetch)=>{
    // Do Magic
  };
}
```

**Comment by 122wr** [comment]
Vai dar certo
