### ISSUE TITLE
stop discovery when start discovery or stop discovery fail?

### ISSUE THREAD

**Issue by tedhenry100** [balthazar/react-native-zeroconf#81]
In the Android NSD article, in section [Discover services on the network](https://developer.android.com/training/connect-devices-wirelessly/nsd#discover), there are the following method implementations. Would the calls to `stopServiceDiscovery` be improvements to the react-native-zeroconf code?

    override fun onStartDiscoveryFailed(serviceType: String, errorCode: Int) {
        Log.e(TAG, "Discovery failed: Error code:$errorCode")
        nsdManager.stopServiceDiscovery(this)
    }

    override fun onStopDiscoveryFailed(serviceType: String, errorCode: Int) {
        Log.e(TAG, "Discovery failed: Error code:$errorCode")
        nsdManager.stopServiceDiscovery(this)
    }

**Comment by balthazar** [comment]
I'm not sure honestly, but trying to stop the discovery in the failed stop discovery failed doesn't seem like a good idea 😂

**Comment by balthazar** [comment]
And trying to stop it if it fails to start the discovery actually doesn't seem right either. If you have any idea of the benefits of this feel free to reopen

**Comment by tedhenry100** [comment]
Thanks for your thoughts.
