### ISSUE TITLE
Add TXT part to the ability to advertise.

### ISSUE THREAD

**Issue by xploSEoF** [balthazar/react-native-zeroconf#91]
Now that the ability to advertise is in (or nearly, see #88) the ability to advertise with TXT records is missing.

**Comment by FrankFundel** [comment]
https://github.com/FrankFundel/react-native-zeroconf
Enabled txt records on android

**Comment by balthazar** [comment]
@FrankFundel rather than create and advertise a fork why won't you do a PR?

**Comment by FrankFundel** [comment]
@balthazar sorry I#M new to this and read here https://stackoverflow.com/questions/50661536/how-do-you-modify-others-library-module to fork the repository. I will do a PR now.

**Comment by dotemacs** [comment]
I guess this can be closed too
